In [3]:
import numpy as np
import pandas as pd
import json

In [4]:
# Load some data
with open("data/league-fixture/big_fixture_data.json") as file:
    data = json.load(file)

{'Premier-League': {'Wk': {'0': 1.0,
   '1': 1.0,
   '2': 1.0,
   '3': 1.0,
   '4': 1.0,
   '5': 1.0,
   '6': 1.0,
   '7': 1.0,
   '8': 1.0,
   '9': 1.0,
   '10': 2.0,
   '11': 2.0,
   '12': 2.0,
   '13': 2.0,
   '14': 2.0,
   '15': 2.0,
   '16': 2.0,
   '17': 2.0,
   '18': 2.0,
   '19': 2.0,
   '20': 3.0,
   '21': 3.0,
   '22': 3.0,
   '23': 3.0,
   '24': 3.0,
   '25': 3.0,
   '26': 3.0,
   '27': 3.0,
   '28': 3.0,
   '29': 3.0,
   '30': 4.0,
   '31': 4.0,
   '32': 4.0,
   '33': 4.0,
   '34': 4.0,
   '35': 4.0,
   '36': 4.0,
   '37': 4.0,
   '38': 4.0,
   '39': 4.0,
   '40': 5.0,
   '41': 5.0,
   '42': 5.0,
   '43': 5.0,
   '44': 5.0,
   '45': 5.0,
   '46': 5.0,
   '47': 5.0,
   '48': 5.0,
   '49': 5.0,
   '50': 6.0,
   '51': 6.0,
   '52': 6.0,
   '53': 6.0,
   '54': 6.0,
   '55': 6.0,
   '56': 6.0,
   '57': 6.0,
   '58': 6.0,
   '59': 6.0,
   '60': 7.0,
   '61': 7.0,
   '62': 7.0,
   '63': 7.0,
   '64': 7.0,
   '65': 7.0,
   '66': 7.0,
   '67': 7.0,
   '68': 7.0,
   '69': 7.0,
   '70': 8.0,
   '71': 8.0,
   '72': 8.0,
   '73': 8.0,
   '74': 8.0,
   '75': 8.0,
   '76': 8.0,
   '77': 8.0,
   '78': 8.0,
   '79': 8.0,
   '80': 9.0,
   '81': 9.0,
   '82': 9.0,
   '83': 9.0,
   '84': 9.0,
   '85': 9.0,
   '86': 9.0,
   '87': 9.0,
   '88': 9.0,
   '89': 9.0,
   '90': 10.0,
   '91': 10.0,
   '92': 10.0,
   '93': 10.0,
   '94': 10.0,
   '95': 10.0,
   '96': 10.0,
   '97': 10.0,
   '98': 10.0,
   '99': 10.0,
   '100': 11.0,
   '101': 11.0,
   '102': 11.0,
   '103': 11.0,
   '104': 11.0,
   '105': 11.0,
   '106': 11.0,
   '107': 11.0,
   '108': 11.0,
   '109': 11.0,
   '110': 12.0,
   '111': 12.0,
   '112': 12.0,
   '113': 12.0,
   '114': 12.0,
   '115': 12.0,
   '116': 12.0,
   '117': 12.0,
   '118': 12.0,
   '119': 12.0,
   '120': 13.0,
   '121': 13.0,
   '122': 13.0,
   '123': 13.0,
   '124': 13.0,
   '125': 13.0,
   '126': 13.0,
   '127': 13.0,
   '128': 13.0,
   '129': 13.0,
   '130': 14.0,
   '131': 14.0,
   '132': 14.0,
   '133': 14.0,
   '134': 14.0,
   '135': 14.0,
   '136': 14.0,
   '137': 14.0,
   '138': 14.0,
   '139': 14.0,
   '140': 15.0,
   '141': 15.0,
   '142': 15.0,
   '143': 15.0,
   '144': 15.0,
   '145': 15.0,
   '146': 15.0,
   '147': 15.0,
   '148': 15.0,
   '149': 15.0,
   '150': 16.0,
   '151': 16.0,
   '152': 16.0,
   '153': 16.0,
   '154': 16.0,
   '155': 16.0,
   '156': 16.0,
   '157': 16.0,
   '158': 16.0,
   '159': 16.0,
   '160': 17.0,
   '161': 17.0,
   '162': 17.0,
   '163': 17.0,
   '164': 17.0,
   '165': 17.0,
   '166': 17.0,
   '167': 17.0,
   '168': 17.0,
   '169': 17.0,
   '170': 18.0,
   '171': 18.0,
   '172': 18.0,
   '173': 18.0,
   '174': 18.0,
   '175': 18.0,
   '176': 18.0,
   '177': 18.0,
   '178': 18.0,
   '179': 18.0,
   '180': 19.0,
   '181': 19.0,
   '182': 19.0,
   '183': 19.0,
   '184': 19.0,
   '185': 19.0,
   '186': 19.0,
   '187': 19.0,
   '188': 19.0,
   '189': 19.0,
   '190': 20.0,
   '191': 20.0,
   '192': 20.0,
   '193': 20.0,
   '194': 20.0,
   '195': 20.0,
   '196': 20.0,
   '197': 20.0,
   '198': 20.0,
   '199': 20.0,
   '200': 21.0,
   '201': 21.0,
   '202': 21.0,
   '203': 21.0,
   '204': 21.0,
   '205': 21.0,
   '206': 21.0,
   '207': 21.0,
   '208': 21.0,
   '209': 22.0,
   '210': 22.0,
   '211': 22.0,
   '212': 22.0,
   '213': 22.0,
   '214': 22.0,
   '215': 22.0,
   '216': 22.0,
   '217': 22.0,
   '218': 22.0,
   '219': 21.0,
   '220': 23.0,
   '221': 23.0,
   '222': 23.0,
   '223': 23.0,
   '224': 23.0,
   '225': 23.0,
   '226': 23.0,
   '227': 23.0,
   '228': 23.0,
   '229': 23.0,
   '230': 24.0,
   '231': 24.0,
   '232': 24.0,
   '233': 24.0,
   '234': 24.0,
   '235': 24.0,
   '236': 24.0,
   '237': 24.0,
   '238': 24.0,
   '239': 24.0,
   '240': 25.0,
   '241': 25.0,
   '242': 25.0,
   '243': 25.0,
   '244': 25.0,
   '245': 25.0,
   '246': 25.0,
   '247': 25.0,
   '248': 25.0,
   '249': 25.0,
   '250': 26.0,
   '251': 26.0,
   '252': 26.0,
   '253': 26.0,
   '254': 26.0,
   '255': 26.0,
   '256': 26.0,
   '257': 26.0,
   '258': 26.0,
   '259': 26.0,
   '260': 27.0,
   '261': 27.0,
   '262': 27.0,
   '263': 27.0,
   '264': 27.0,
   '265': 27.0,
   '266': 27.0,
   '267': 27.0,
   '268': 27.0,
   '269': 27.0,
   '270': 28.0,
   '271': 28.0,
   '272': 28.0,
   '273': 28.0,
   '274': 28.0,
   '275': 28.0,
   '276': 28.0,
   '277': 28.0,
   '278': 28.0,
   '279': 28.0,
   '280': 29.0,
   '281': 29.0,
   '282': 29.0,
   '283': 29.0,
   '284': 29.0,
   '285': 29.0,
   '286': 29.0,
   '287': 29.0,
   '288': 29.0,
   '289': 29.0,
   '290': 30.0,
   '291': 30.0,
   '292': 30.0,
   '293': 30.0,
   '294': 30.0,
   '295': 30.0,
   '296': 30.0,
   '297': 30.0,
   '298': 30.0,
   '299': 30.0,
   '300': 31.0,
   '301': 31.0,
   '302': 31.0,
   '303': 31.0,
   '304': 32.0,
   '305': 32.0,
   '306': 32.0,
   '307': 32.0,
   '308': 32.0,
   '309': 32.0,
   '310': 32.0,
   '311': 32.0,
   '312': 32.0,
   '313': 32.0,
   '314': 33.0,
   '315': 33.0,
   '316': 33.0,
   '317': 33.0,
   '318': 33.0,
   '319': 33.0,
   '320': 33.0,
   '321': 33.0,
   '322': 33.0,
   '323': 33.0,
   '324': 34.0,
   '325': 34.0,
   '326': 34.0,
   '327': 34.0,
   '328': 34.0,
   '329': 34.0,
   '330': 34.0,
   '331': 34.0,
   '332': 34.0,
   '333': 34.0,
   '334': 35.0,
   '335': 35.0,
   '336': 31.0,
   '337': 35.0,
   '338': 35.0,
   '339': 35.0,
   '340': 35.0,
   '341': 35.0,
   '342': 35.0,
   '343': 35.0,
   '344': 36.0,
   '345': 36.0,
   '346': 36.0,
   '347': 36.0,
   '348': 36.0,
   '349': 36.0,
   '350': 36.0,
   '351': 36.0,
   '352': 36.0,
   '353': 36.0,
   '354': 37.0,
   '355': 37.0,
   '356': 37.0,
   '357': 37.0,
   '358': 37.0,
   '359': 37.0,
   '360': 37.0,
   '361': 37.0,
   '362': 37.0,
   '363': 37.0,
   '364': 31.0,
   '365': 31.0,
   '366': 35.0,
   '367': 31.0,
   '368': 31.0,
   '369': 31.0,
   '370': 38.0,
   '371': 38.0,
   '372': 38.0,
   '373': 38.0,
   '374': 38.0,
   '375': 38.0,
   '376': 38.0,
   '377': 38.0,
   '378': 38.0,
   '379': 38.0},
  'Day': {'0': 'Fri',
   '1': 'Sat',
   '2': 'Sat',
   '3': 'Sat',
   '4': 'Sat',
   '5': 'Sat',
   '6': 'Sat',
   '7': 'Sat',
   '8': 'Sun',
   '9': 'Sun',
   '10': 'Sat',
   '11': 'Sat',
   '12': 'Sat',
   '13': 'Sat',
   '14': 'Sat',
   '15': 'Sat',
   '16': 'Sat',
   '17': 'Sun',
   '18': 'Sun',
   '19': 'Mon',
   '20': 'Sat',
   '21': 'Sat',
   '22': 'Sat',
   '23': 'Sat',
   '24': 'Sat',
   '25': 'Sat',
   '26': 'Sun',
   '27': 'Sun',
   '28': 'Sun',
   '29': 'Sun',
   '30': 'Sat',
   '31': 'Sat',
   '32': 'Sat',
   '33': 'Sat',
   '34': 'Sat',
   '35': 'Sat',
   '36': 'Sat',
   '37': 'Sun',
   '38': 'Sun',
   '39': 'Mon',
   '40': 'Fri',
   '41': 'Sat',
   '42': 'Sat',
   '43': 'Sat',
   '44': 'Sat',
   '45': 'Sat',
   '46': 'Sat',
   '47': 'Sat',
   '48': 'Sun',
   '49': 'Sun',
   '50': 'Sat',
   '51': 'Sat',
   '52': 'Sat',
   '53': 'Sat',
   '54': 'Sat',
   '55': 'Sat',
   '56': 'Sat',
   '57': 'Sat',
   '58': 'Sun',
   '59': 'Mon',
   '60': 'Sat',
   '61': 'Sat',
   '62': 'Sat',
   '63': 'Sat',
   '64': 'Sat',
   '65': 'Sat',
   '66': 'Sat',
   '67': 'Sun',
   '68': 'Sun',
   '69': 'Sun',
   '70': 'Sat',
   '71': 'Sat',
   '72': 'Sat',
   '73': 'Sat',
   '74': 'Sat',
   '75': 'Sat',
   '76': 'Sat',
   '77': 'Sun',
   '78': 'Sun',
   '79': 'Mon',
   '80': 'Fri',
   '81': 'Sat',
   '82': 'Sat',
   '83': 'Sat',
   '84': 'Sat',
   '85': 'Sat',
   '86': 'Sat',
   '87': 'Sat',
   '88': 'Sun',
   '89': 'Sun',
   '90': 'Sat',
   '91': 'Sat',
   '92': 'Sat',
   '93': 'Sat',
   '94': 'Sat',
   '95': 'Sat',
   '96': 'Sat',
   '97': 'Sun',
   '98': 'Sun',
   '99': 'Mon',
   '100': 'Sat',
   '101': 'Sat',
   '102': 'Sat',
   '103': 'Sat',
   '104': 'Sat',
   '105': 'Sat',
   '106': 'Sun',
   '107': 'Sun',
   '108': 'Sun',
   '109': 'Sun',
   '110': 'Sat',
   '111': 'Sat',
   '112': 'Sat',
   '113': 'Sat',
   '114': 'Sat',
   '115': 'Sat',
   '116': 'Sat',
   '117': 'Sat',
   '118': 'Sun',
   '119': 'Mon',
   '120': 'Fri',
   '121': 'Sat',
   '122': 'Sat',
   '123': 'Sat',
   '124': 'Sat',
   '125': 'Sat',
   '126': 'Sat',
   '127': 'Sun',
   '128': 'Sun',
   '129': 'Sun',
   '130': 'Tue',
   '131': 'Tue',
   '132': 'Tue',
   '133': 'Tue',
   '134': 'Wed',
   '135': 'Wed',
   '136': 'Wed',
   '137': 'Wed',
   '138': 'Wed',
   '139': 'Wed',
   '140': 'Sat',
   '141': 'Sat',
   '142': 'Sat',
   '143': 'Sat',
   '144': 'Sat',
   '145': 'Sat',
   '146': 'Sat',
   '147': 'Sat',
   '148': 'Sun',
   '149': 'Sun',
   '150': 'Sat',
   '151': 'Sat',
   '152': 'Sat',
   '153': 'Sat',
   '154': 'Sat',
   '155': 'Sat',
   '156': 'Sat',
   '157': 'Sun',
   '158': 'Sun',
   '159': 'Sun',
   '160': 'Tue',
   '161': 'Tue',
   '162': 'Tue',
   '163': 'Wed',
   '164': 'Wed',
   '165': 'Wed',
   '166': 'Wed',
   '167': 'Wed',
   '168': 'Wed',
   '169': 'Wed',
   '170': 'Sat',
   '171': 'Sat',
   '172': 'Sat',
   '173': 'Sat',
   '174': 'Sat',
   '175': 'Sat',
   '176': 'Sat',
   '177': 'Sun',
   '178': 'Sun',
   '179': 'Mon',
   '180': 'Fri',
   '181': 'Sat',
   '182': 'Sat',
   '183': 'Sat',
   '184': 'Sat',
   '185': 'Sat',
   '186': 'Sat',
   '187': 'Sat',
   '188': 'Sat',
   '189': 'Sat',
   '190': 'Tue',
   '191': 'Tue',
   '192': 'Tue',
   '193': 'Tue',
   '194': 'Tue',
   '195': 'Tue',
   '196': 'Tue',
   '197': 'Tue',
   '198': 'Wed',
   '199': 'Thu',
   '200': 'Sat',
   '201': 'Sat',
   '202': 'Sat',
   '203': 'Sat',
   '204': 'Sat',
   '205': 'Sat',
   '206': 'Sat',
   '207': 'Sun',
   '208': 'Sun',
   '209': 'Mon',
   '210': 'Mon',
   '211': 'Mon',
   '212': 'Mon',
   '213': 'Mon',
   '214': 'Tue',
   '215': 'Tue',
   '216': 'Tue',
   '217': 'Tue',
   '218': 'Wed',
   '219': 'Thu',
   '220': 'Sat',
   '221': 'Sat',
   '222': 'Sat',
   '223': 'Sat',
   '224': 'Sat',
   '225': 'Sat',
   '226': 'Sat',
   '227': 'Sun',
   '228': 'Sun',
   '229': 'Mon',
   '230': 'Sat',
   '231': 'Sat',
   '232': 'Sat',
   '233': 'Sat',
   '234': 'Sat',
   '235': 'Sat',
   '236': 'Sat',
   '237': 'Sat',
   '238': 'Sun',
   '239': 'Mon',
   '240': 'Tue',
   '241': 'Tue',
   '242': 'Tue',
   '243': 'Wed',
   '244': 'Wed',
   '245': 'Wed',
   '246': 'Wed',
   '247': 'Wed',
   '248': 'Wed',
   '249': 'Wed',
   '250': 'Sat',
   '251': 'Sat',
   '252': 'Sat',
   '253': 'Sat',
   '254': 'Sat',
   '255': 'Sat',
   '256': 'Sat',
   '257': 'Sun',
   '258': 'Sun',
   '259': 'Mon',
   '260': 'Sat',
   '261': 'Sat',
   '262': 'Sat',
   '263': 'Sat',
   '264': 'Sat',
   '265': 'Sat',
   '266': 'Sun',
   '267': 'Sun',
   '268': 'Sun',
   '269': 'Mon',
   '270': 'Sat',
   '271': 'Sat',
   '272': 'Sat',
   '273': 'Sat',
   '274': 'Sat',
   '275': 'Sat',
   '276': 'Sat',
   '277': 'Sun',
   '278': 'Sun',
   '279': 'Thu',
   '280': 'Sat',
   '281': 'Sat',
   '282': 'Sat',
   '283': 'Sat',
   '284': 'Sat',
   '285': 'Sat',
   '286': 'Sat',
   '287': 'Sun',
   '288': 'Sun',
   '289': 'Mon',
   '290': 'Sat',
   '291': 'Sat',
   '292': 'Sat',
   '293': 'Sat',
   '294': 'Sat',
   '295': 'Sat',
   '296': 'Sat',
   '297': 'Sun',
   '298': 'Sun',
   '299': 'Mon',
   '300': 'Sat',
   '301': 'Sat',
   '302': 'Sat',
   '303': 'Sat',
   '304': 'Sat',
   '305': 'Sat',
   '306': 'Sat',
   '307': 'Sat',
   '308': 'Sat',
   '309': 'Sat',
   '310': 'Sat',
   '311': 'Sat',
   '312': 'Sun',
   '313': 'Sun',
   '314': 'Sat',
   '315': 'Sat',
   '316': 'Sat',
   '317': 'Sat',
   '318': 'Sat',
   '319': 'Sat',
   '320': 'Sat',
   '321': 'Sat',
   '322': 'Sun',
   '323': 'Sun',
   '324': 'Sat',
   '325': 'Sat',
   '326': 'Sat',
   '327': 'Sat',
   '328': 'Sat',
   '329': 'Sat',
   '330': 'Sat',
   '331': 'Sun',
   '332': 'Sun',
   '333': 'Mon',
   '334': 'Tue',
   '335': 'Wed',
   '336': 'Thu',
   '337': 'Thu',
   '338': 'Sat',
   '339': 'Sat',
   '340': 'Sun',
   '341': 'Sun',
   '342': 'Sun',
   '343': 'Mon',
   '344': 'Sat',
   '345': 'Sat',
   '346': 'Sat',
   '347': 'Sat',
   '348': 'Sat',
   '349': 'Sat',
   '350': 'Sat',
   '351': 'Sun',
   '352': 'Sun',
   '353': 'Mon',
   '354': 'Fri',
   '355': 'Sat',
   '356': 'Sat',
   '357': 'Sat',
   '358': 'Sat',
   '359': 'Sat',
   '360': 'Sat',
   '361': 'Sun',
   '362': 'Sun',
   '363': 'Sun',
   '364': 'Tue',
   '365': 'Wed',
   '366': 'Wed',
   '367': 'Wed',
   '368': 'Wed',
   '369': 'Thu',
   '370': 'Sun',
   '371': 'Sun',
   '372': 'Sun',
   '373': 'Sun',
   '374': 'Sun',
   '375': 'Sun',
   '376': 'Sun',
   '377': 'Sun',
   '378': 'Sun',
   '379': 'Sun'},
  'Date': {'0': '2017-08-11',
   '1': '2017-08-12',
   '2': '2017-08-12',
   '3': '2017-08-12',
   '4': '2017-08-12',
   '5': '2017-08-12',
   '6': '2017-08-12',
   '7': '2017-08-12',
   '8': '2017-08-13',
   '9': '2017-08-13',
   '10': '2017-08-19',
   '11': '2017-08-19',
   '12': '2017-08-19',
   '13': '2017-08-19',
   '14': '2017-08-19',
   '15': '2017-08-19',
   '16': '2017-08-19',
   '17': '2017-08-20',
   '18': '2017-08-20',
   '19': '2017-08-21',
   '20': '2017-08-26',
   '21': '2017-08-26',
   '22': '2017-08-26',
   '23': '2017-08-26',
   '24': '2017-08-26',
   '25': '2017-08-26',
   '26': '2017-08-27',
   '27': '2017-08-27',
   '28': '2017-08-27',
   '29': '2017-08-27',
   '30': '2017-09-09',
   '31': '2017-09-09',
   '32': '2017-09-09',
   '33': '2017-09-09',
   '34': '2017-09-09',
   '35': '2017-09-09',
   '36': '2017-09-09',
   '37': '2017-09-10',
   '38': '2017-09-10',
   '39': '2017-09-11',
   '40': '2017-09-15',
   '41': '2017-09-16',
   '42': '2017-09-16',
   '43': '2017-09-16',
   '44': '2017-09-16',
   '45': '2017-09-16',
   '46': '2017-09-16',
   '47': '2017-09-16',
   '48': '2017-09-17',
   '49': '2017-09-17',
   '50': '2017-09-23',
   '51': '2017-09-23',
   '52': '2017-09-23',
   '53': '2017-09-23',
   '54': '2017-09-23',
   '55': '2017-09-23',
   '56': '2017-09-23',
   '57': '2017-09-23',
   '58': '2017-09-24',
   '59': '2017-09-25',
   '60': '2017-09-30',
   '61': '2017-09-30',
   '62': '2017-09-30',
   '63': '2017-09-30',
   '64': '2017-09-30',
   '65': '2017-09-30',
   '66': '2017-09-30',
   '67': '2017-10-01',
   '68': '2017-10-01',
   '69': '2017-10-01',
   '70': '2017-10-14',
   '71': '2017-10-14',
   '72': '2017-10-14',
   '73': '2017-10-14',
   '74': '2017-10-14',
   '75': '2017-10-14',
   '76': '2017-10-14',
   '77': '2017-10-15',
   '78': '2017-10-15',
   '79': '2017-10-16',
   '80': '2017-10-20',
   '81': '2017-10-21',
   '82': '2017-10-21',
   '83': '2017-10-21',
   '84': '2017-10-21',
   '85': '2017-10-21',
   '86': '2017-10-21',
   '87': '2017-10-21',
   '88': '2017-10-22',
   '89': '2017-10-22',
   '90': '2017-10-28',
   '91': '2017-10-28',
   '92': '2017-10-28',
   '93': '2017-10-28',
   '94': '2017-10-28',
   '95': '2017-10-28',
   '96': '2017-10-28',
   '97': '2017-10-29',
   '98': '2017-10-29',
   '99': '2017-10-30',
   '100': '2017-11-04',
   '101': '2017-11-04',
   '102': '2017-11-04',
   '103': '2017-11-04',
   '104': '2017-11-04',
   '105': '2017-11-04',
   '106': '2017-11-05',
   '107': '2017-11-05',
   '108': '2017-11-05',
   '109': '2017-11-05',
   '110': '2017-11-18',
   '111': '2017-11-18',
   '112': '2017-11-18',
   '113': '2017-11-18',
   '114': '2017-11-18',
   '115': '2017-11-18',
   '116': '2017-11-18',
   '117': '2017-11-18',
   '118': '2017-11-19',
   '119': '2017-11-20',
   '120': '2017-11-24',
   '121': '2017-11-25',
   '122': '2017-11-25',
   '123': '2017-11-25',
   '124': '2017-11-25',
   '125': '2017-11-25',
   '126': '2017-11-25',
   '127': '2017-11-26',
   '128': '2017-11-26',
   '129': '2017-11-26',
   '130': '2017-11-28',
   '131': '2017-11-28',
   '132': '2017-11-28',
   '133': '2017-11-28',
   '134': '2017-11-29',
   '135': '2017-11-29',
   '136': '2017-11-29',
   '137': '2017-11-29',
   '138': '2017-11-29',
   '139': '2017-11-29',
   '140': '2017-12-02',
   '141': '2017-12-02',
   '142': '2017-12-02',
   '143': '2017-12-02',
   '144': '2017-12-02',
   '145': '2017-12-02',
   '146': '2017-12-02',
   '147': '2017-12-02',
   '148': '2017-12-03',
   '149': '2017-12-03',
   '150': '2017-12-09',
   '151': '2017-12-09',
   '152': '2017-12-09',
   '153': '2017-12-09',
   '154': '2017-12-09',
   '155': '2017-12-09',
   '156': '2017-12-09',
   '157': '2017-12-10',
   '158': '2017-12-10',
   '159': '2017-12-10',
   '160': '2017-12-12',
   '161': '2017-12-12',
   '162': '2017-12-12',
   '163': '2017-12-13',
   '164': '2017-12-13',
   '165': '2017-12-13',
   '166': '2017-12-13',
   '167': '2017-12-13',
   '168': '2017-12-13',
   '169': '2017-12-13',
   '170': '2017-12-16',
   '171': '2017-12-16',
   '172': '2017-12-16',
   '173': '2017-12-16',
   '174': '2017-12-16',
   '175': '2017-12-16',
   '176': '2017-12-16',
   '177': '2017-12-17',
   '178': '2017-12-17',
   '179': '2017-12-18',
   '180': '2017-12-22',
   '181': '2017-12-23',
   '182': '2017-12-23',
   '183': '2017-12-23',
   '184': '2017-12-23',
   '185': '2017-12-23',
   '186': '2017-12-23',
   '187': '2017-12-23',
   '188': '2017-12-23',
   '189': '2017-12-23',
   '190': '2017-12-26',
   '191': '2017-12-26',
   '192': '2017-12-26',
   '193': '2017-12-26',
   '194': '2017-12-26',
   '195': '2017-12-26',
   '196': '2017-12-26',
   '197': '2017-12-26',
   '198': '2017-12-27',
   '199': '2017-12-28',
   '200': '2017-12-30',
   '201': '2017-12-30',
   '202': '2017-12-30',
   '203': '2017-12-30',
   '204': '2017-12-30',
   '205': '2017-12-30',
   '206': '2017-12-30',
   '207': '2017-12-31',
   '208': '2017-12-31',
   '209': '2018-01-01',
   '210': '2018-01-01',
   '211': '2018-01-01',
   '212': '2018-01-01',
   '213': '2018-01-01',
   '214': '2018-01-02',
   '215': '2018-01-02',
   '216': '2018-01-02',
   '217': '2018-01-02',
   '218': '2018-01-03',
   '219': '2018-01-04',
   '220': '2018-01-13',
   '221': '2018-01-13',
   '222': '2018-01-13',
   '223': '2018-01-13',
   '224': '2018-01-13',
   '225': '2018-01-13',
   '226': '2018-01-13',
   '227': '2018-01-14',
   '228': '2018-01-14',
   '229': '2018-01-15',
   '230': '2018-01-20',
   '231': '2018-01-20',
   '232': '2018-01-20',
   '233': '2018-01-20',
   '234': '2018-01-20',
   '235': '2018-01-20',
   '236': '2018-01-20',
   '237': '2018-01-20',
   '238': '2018-01-21',
   '239': '2018-01-22',
   '240': '2018-01-30',
   '241': '2018-01-30',
   '242': '2018-01-30',
   '243': '2018-01-31',
   '244': '2018-01-31',
   '245': '2018-01-31',
   '246': '2018-01-31',
   '247': '2018-01-31',
   '248': '2018-01-31',
   '249': '2018-01-31',
   '250': '2018-02-03',
   '251': '2018-02-03',
   '252': '2018-02-03',
   '253': '2018-02-03',
   '254': '2018-02-03',
   '255': '2018-02-03',
   '256': '2018-02-03',
   '257': '2018-02-04',
   '258': '2018-02-04',
   '259': '2018-02-05',
   '260': '2018-02-10',
   '261': '2018-02-10',
   '262': '2018-02-10',
   '263': '2018-02-10',
   '264': '2018-02-10',
   '265': '2018-02-10',
   '266': '2018-02-11',
   '267': '2018-02-11',
   '268': '2018-02-11',
   '269': '2018-02-12',
   '270': '2018-02-24',
   '271': '2018-02-24',
   '272': '2018-02-24',
   '273': '2018-02-24',
   '274': '2018-02-24',
   '275': '2018-02-24',
   '276': '2018-02-24',
   '277': '2018-02-25',
   '278': '2018-02-25',
   '279': '2018-03-01',
   '280': '2018-03-03',
   '281': '2018-03-03',
   '282': '2018-03-03',
   '283': '2018-03-03',
   '284': '2018-03-03',
   '285': '2018-03-03',
   '286': '2018-03-03',
   '287': '2018-03-04',
   '288': '2018-03-04',
   '289': '2018-03-05',
   '290': '2018-03-10',
   '291': '2018-03-10',
   '292': '2018-03-10',
   '293': '2018-03-10',
   '294': '2018-03-10',
   '295': '2018-03-10',
   '296': '2018-03-10',
   '297': '2018-03-11',
   '298': '2018-03-11',
   '299': '2018-03-12',
   '300': '2018-03-17',
   '301': '2018-03-17',
   '302': '2018-03-17',
   '303': '2018-03-17',
   '304': '2018-03-31',
   '305': '2018-03-31',
   '306': '2018-03-31',
   '307': '2018-03-31',
   '308': '2018-03-31',
   '309': '2018-03-31',
   '310': '2018-03-31',
   '311': '2018-03-31',
   '312': '2018-04-01',
   '313': '2018-04-01',
   '314': '2018-04-07',
   '315': '2018-04-07',
   '316': '2018-04-07',
   '317': '2018-04-07',
   '318': '2018-04-07',
   '319': '2018-04-07',
   '320': '2018-04-07',
   '321': '2018-04-07',
   '322': '2018-04-08',
   '323': '2018-04-08',
   '324': '2018-04-14',
   '325': '2018-04-14',

In [49]:
last_season_data = data["2023-2024"]
df = pd.DataFrame()
for k, v in last_season_data.items():
    v = pd.DataFrame.from_dict(v)
    v["league"] = k
    df = pd.concat([df, v])

df.reset_index(drop=True, inplace=True)
df.head()

,Wk,Day,Date,Time,Home,Away,xG,xG.1,Score,Attendance,...,t2_clearances,t1_offsides,t2_offsides,t1_goal_kicks,t2_goal_kicks,t1_throw_ins,t2_throw_ins,t1_long_balls,t2_long_balls,league
0,1.0,Fri,2023-08-11,20:00,Burnley,Manchester City,0.3,1.9,0–3,21572.0,...,7.0,0.0,1.0,5.0,7.0,15.0,13.0,65.0,77.0,Premier-League
1,1.0,Sat,2023-08-12,12:30,Arsenal,Nott'ham Forest,0.8,1.2,2–1,59984.0,...,18.0,2.0,1.0,8.0,5.0,18.0,9.0,38.0,54.0,Premier-League
2,1.0,Sat,2023-08-12,15:00,Everton,Fulham,2.7,1.5,0–1,39940.0,...,31.0,6.0,3.0,9.0,7.0,27.0,22.0,76.0,53.0,Premier-League
3,1.0,Sat,2023-08-12,15:00,Brighton,Luton Town,4.0,1.5,4–1,31872.0,...,28.0,2.0,3.0,8.0,11.0,16.0,11.0,42.0,73.0,Premier-League
4,1.0,Sat,2023-08-12,15:00,Sheffield Utd,Crystal Palace,0.5,1.9,0–1,31194.0,...,16.0,2.0,2.0,10.0,6.0,18.0,31.0,81.0,72.0,Premier-League

In [50]:
df.groupby("league").size()

league
Bundesliga        306
La-Liga           380
Ligue-1           306
Premier-League    380
Serie-A           380
dtype: int64

In [58]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1752 entries, 0 to 1751
Data columns (total 53 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Wk                1748 non-null   float64
 1   Day               1748 non-null   object
 2   Date              1748 non-null   object
 3   Time              1748 non-null   object
 4   Home              1748 non-null   object
 5   Away              1748 non-null   object
 6   xG                1748 non-null   float64
 7   xG.1              1748 non-null   float64
 8   Score             1748 non-null   object
 9   Attendance        1748 non-null   float64
 10  Referee           1748 non-null   object
 11  season            1748 non-null   object
 12  t1_captain        1751 non-null   object
 13  t2_captain        1751 non-null   object
 14  t1_formation      1751 non-null   object
 15  t2_formation      1751 non-null   object
 16  t1_possession     1751 non-null   object
 17  t2_possession     1751 non-null   object
 18  t1_passing        1751 non-null   object
 19  t2_passing        1751 non-null   object
 20  t1_shots          1751 non-null   object
 21  t2_shots          1751 non-null   object
 22  t1_saves          1751 non-null   object
 23  t2_saves          1751 non-null   object
 24  t1_yellow_cards   1751 non-null   float64
 25  t1_red_cards      1751 non-null   float64
 26  t2_yellow_cards   1751 non-null   float64
 27  t2_red_cards      1751 non-null   float64
 28  t1_fouls          1751 non-null   float64
 29  t2_fouls          1751 non-null   float64
 30  t1_corners        1751 non-null   float64
 31  t2_corners        1751 non-null   float64
 32  t1_crosses        1751 non-null   float64
 33  t2_crosses        1751 non-null   float64
 34  t1_touches        1751 non-null   float64
 35  t2_touches        1751 non-null   float64
 36  t1_tackles        1751 non-null   float64
 37  t2_tackles        1751 non-null   float64
 38  t1_interceptions  1751 non-null   float64
 39  t2_interceptions  1751 non-null   float64
 40  t1_aerials_won    1751 non-null   float64
 41  t2_aerials_won    1751 non-null   float64
 42  t1_clearances     1751 non-null   float64
 43  t2_clearances     1751 non-null   float64
 44  t1_offsides       1751 non-null   float64
 45  t2_offsides       1751 non-null   float64
 46  t1_goal_kicks     1751 non-null   float64
 47  t2_goal_kicks     1751 non-null   float64
 48  t1_throw_ins      1751 non-null   float64
 49  t2_throw_ins      1751 non-null   float64
 50  t1_long_balls     1751 non-null   float64
 51  t2_long_balls     1751 non-null   float64
 52  league            1752 non-null   object
dtypes: float64(32), object(21)
memory usage: 725.6+ KB
None
                Wk           xG         xG.1    Attendance  t1_yellow_cards  \
count  1748.000000  1748.000000  1748.000000   1748.000000      1751.000000
mean     18.792906     1.564817     1.216419  33017.201945         2.069674
std      10.625676     0.861445     0.731740  18308.248789         1.508263
min       1.000000     0.100000     0.000000   4231.000000         0.000000
25%      10.000000     0.900000     0.700000  17810.000000         1.000000
50%      19.000000     1.400000     1.100000  28482.000000         2.000000
75%      28.000000     2.100000     1.600000  45000.000000         3.000000
max      38.000000     7.000000     4.500000  81365.000000        10.500000

       t1_red_cards  t2_yellow_cards  t2_red_cards     t1_fouls     t2_fouls  \
count   1751.000000      1751.000000   1751.000000  1751.000000  1751.000000
mean       0.060537         2.383210      0.054826    11.750999    12.168475
std        0.247944         1.551104      0.239925     3.772944     3.825127
min        0.000000         0.000000      0.000000     2.000000     2.000000
25%        0.000000         1.000000      0.000000     9.000000    10.000000
50%        0.000000         2.000000      0.000000    12.000000    12.000000
75%        0.000000         3.000000      0.000000    14.000000    15.000000
max        2.000000         9.500000      2.000000    28.000000    31.000000

       ...  t1_clearances  t2_clearances  t1_offsides  t2_offsides  \
count  ...    1751.000000    1751.000000  1751.000000  1751.000000
mean   ...      17.623644      21.798401     1.904055     1.718447
std    ...       8.085012       9.227036     1.675006     1.522816
min    ...       1.000000       2.000000     0.000000     0.000000
25%    ...      12.000000      15.000000     1.000000     1.000000
50%    ...      16.000000      20.000000     2.000000     1.000000
75%    ...      22.000000      28.000000     3.000000     2.000000
max    ...      58.000000      67.000000    10.000000    14.000000

       t1_goal_kicks  t2_goal_kicks  t1_throw_ins  t2_throw_ins  \
count    1751.000000    1751.000000   1751.000000   1751.000000
mean        6.878355       8.243861     19.645917     18.331239
std         3.020604       3.462359      5.921026      5.711436
min         0.000000       0.000000      5.000000      4.000000
25%         5.000000       6.000000     15.000000     14.000000
50%         7.000000       8.000000     19.000000     18.000000
75%         9.000000      10.000000     23.000000     22.000000
max        18.000000      23.000000     42.000000     38.000000

       t1_long_balls  t2_long_balls
count    1751.000000    1751.000000
mean       64.604797      64.152484
std        15.058297      14.734649
min        20.000000      26.000000
25%        54.000000      54.000000
50%        63.000000      63.000000
75%        75.000000      74.000000
max       118.000000     120.000000

[8 rows x 32 columns]

In [84]:
# I want to look into the leagues that have the least amount of goals scored
# I will add a column of the total goals scored in a game
df.dropna(subset=["Score"], inplace=True)
df["home_goals"] = df["Score"].str[0]
df["away_goals"] = df["Score"].str[-1]
df = df.astype({"home_goals": "int32", "away_goals": "int32"})
df.dtypes

df.groupby("league")[["home_goals", "away_goals"]].sum()

                home_goals  away_goals
league
Bundesliga             553         432
La-Liga                564         441
Ligue-1                441         379
Premier-League         684         562
Serie-A                541         441

In [75]:
sum(df["home_goals"])

TypeError: unsupported operand type(s) for +: 'int' and 'str'